export const QuizData = [
  {
    id: 1,
    title: "question 1",
    question: {
      q: "the question",
      a: "answer",
      b: "answer",
      c: "answer",
      d: "answer",
    },
    id: 2,
    title: "question 2",
    question: {
      q: "the question",
      a: "answer",
      b: "answer",
      c: "answer",
      d: "answer",
    },
    id: 3,
    title: "question 3",
    question: {
      q: "the question",
      a: "answer",
      b: "answer",
      c: "answer",
      d: "answer",
    },
    id: 4,
    title: "question 4",
    question: {
      q: "the question",
      a: "answer",
      b: "answer",
      c: "answer",
      d: "answer",
    },
    id: 5,
    title: "question 5",
    question: {
      q: "the question",
      a: "answer",
      b: "answer",
      c: "answer",
      d: "answer",
    },
    id: 6,
    title: "question 6",
    question: {
      q: "the question",
      a: "answer",
      b: "answer",
      c: "answer",
      d: "answer",
    },
  },
];
